version: "3"
services:
    api:
        build:
            dockerfile: ".docker/Dockerfile-dev"
            context: "./packages/api"
        environment:
            - "PORT=${API_PORT}"
            - "DB_HOST=${DB_HOST}"
            - "DB_USER=${DB_USER}"
            - "DB_NAME=${DB_NAME}"
            - "DB_PASSWORD=${DB_PASSWORD}"
        ports:
            - "${API_PORT}:${API_PORT}"
            - "9229:9229"
        volumes:
            - "./packages/api:/home/node/app/:cached"
            - "/home/node/app/node_modules"

    db:
        image: postgres
        restart: always
        environment:
            - "POSTGRES_PASSWORD=${DB_PASSWORD}"
            - "POSTGRES_USER=${DB_USER}"
            - "POSTGRES_DB=${DB_NAME}"
        volumes:
            - ./packages/db/.docker/data:/var/lib/postgresql/data
    db-admin:
        image: adminer
        restart: always
        ports:
            - "8080:8080"